import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@vendfront.com',
      password: bcrypt.hashSync('1234567'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Bike 1',
      slug: 'bike-1',
      category: 'Transportation',
      image: '/images/bike1.jpg',
      price: 1000,
      brand: 'Recon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bike',
    },
    {
      name: 'Bike 2',
      slug: 'bike-2',
      category: 'Transportation',
      image: '/images/bike2.jpg',
      price: 80,
      brand: 'Bird',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bike',
    },
    {
      name: 'Prouduct 1',
      slug: 'slim-shirt',
      category: 'Transportation',
      image: '/images/scooter1.jpg',
      price: 90,
      brand: 'scooter',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Product 2',
      slug: 'golf-pants',
      category: 'Transportation',
      image: '/images/scooter2.jpg',
      price: 90,
      brand: 'scooter',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Product 3',
      slug: 'fit-pants',
      category: 'Transportation',
      image: '/images/scooter3.jpg',
      price: 95,
      brand: 'scooter',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Product 4',
      slug: 'classic-pants',
      category: 'Transportation',
      image: '/images/scooter4.jpg',
      price: 75,
      brand: 'scooter',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular scooter',
    },
  ],
};
export default data;
