import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Super 73-S1',
      slug: 'super73',
      category: 'Transportation',
      image: '/images/bike1.jpg',
      isFeatured: true,
      // featuredImage: '/images/banner1.jpg',
      price: 1995.00,
      brand: 'Super 73',
      rating: 4.5,
      numReviews: 0,
      countInStock: 5,
      description: 'A popular electric bike',
    },
    {
      name: 'RECON bike',
      slug: 'recon',
      category: 'Transportation',
      image: '/images/bike2.jpg',
      isFeatured: true,
      featuredImage: '/images/bike2.jpg',
      price: 2950.00,
      brand: 'Recon',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bike',
    },
    {
      name: 'Basic Electric Scooter',
      slug: 'scooter',
      category: 'Transportation',
      image: '/images/scooter1.jpg',
      price: 249.99,
      brand: 'Ninebot',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A affordable scooter',
    },
    {
      name: 'Big Boy Scooter',
      slug: 'bigboyscooter',
      category: 'Transportation',
      image: '/images/scooter2.jpg',
      price: 499.99,
      brand: 'Fast',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "You'll have no problem getting around",
    },
    {
      name: 'Bird Scooter',
      slug: 'birdscooter',
      category: 'Transportation',
      image: '/images/scooter3.jpg',
      price: 199.99,
      brand: 'Bird',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A classic',
    },
    {
      name: 'Onewheel',
      slug: 'onewheel',
      category: 'Transportation',
      image: '/images/scooter4.jpg',
      price: 950,
      brand: 'Onewheel',
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: 'Onewheel is a ton of fun',
    },
  ],
};
export default data;
