const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/scooter2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/scooter1.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/scooter3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'RECON',
      slug: 'Electric Bike',
      category: 'Pants',
      image: '/images/bike2.jpg',
      price: 90000,
      brand: 'CAB',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Zoom zoom',
    },
    {
      name: 'Super73',
      slug: 'Electric',
      category: 'Bike',
      image: '/images/bike1.jpg',
      price: 2000,
      brand: 'Super73',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'OneWheel',
      slug: 'Electric',
      category: 'Riding',
      image: '/images/scooter4.jpg',
      price: 300,
      brand: 'OneWheel',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular choice',
    },
  ],
};
export default data;
